require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SizePaysController do

  # This should return the minimal set of attributes required to create a valid
  # SizePay. As you add validations to SizePay, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SizePaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all size_pays as @size_pays" do
      size_pay = SizePay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:size_pays).should eq([size_pay])
    end
  end

  describe "GET show" do
    it "assigns the requested size_pay as @size_pay" do
      size_pay = SizePay.create! valid_attributes
      get :show, {:id => size_pay.to_param}, valid_session
      assigns(:size_pay).should eq(size_pay)
    end
  end

  describe "GET new" do
    it "assigns a new size_pay as @size_pay" do
      get :new, {}, valid_session
      assigns(:size_pay).should be_a_new(SizePay)
    end
  end

  describe "GET edit" do
    it "assigns the requested size_pay as @size_pay" do
      size_pay = SizePay.create! valid_attributes
      get :edit, {:id => size_pay.to_param}, valid_session
      assigns(:size_pay).should eq(size_pay)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SizePay" do
        expect {
          post :create, {:size_pay => valid_attributes}, valid_session
        }.to change(SizePay, :count).by(1)
      end

      it "assigns a newly created size_pay as @size_pay" do
        post :create, {:size_pay => valid_attributes}, valid_session
        assigns(:size_pay).should be_a(SizePay)
        assigns(:size_pay).should be_persisted
      end

      it "redirects to the created size_pay" do
        post :create, {:size_pay => valid_attributes}, valid_session
        response.should redirect_to(SizePay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved size_pay as @size_pay" do
        # Trigger the behavior that occurs when invalid params are submitted
        SizePay.any_instance.stub(:save).and_return(false)
        post :create, {:size_pay => {  }}, valid_session
        assigns(:size_pay).should be_a_new(SizePay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SizePay.any_instance.stub(:save).and_return(false)
        post :create, {:size_pay => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested size_pay" do
        size_pay = SizePay.create! valid_attributes
        # Assuming there are no other size_pays in the database, this
        # specifies that the SizePay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SizePay.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => size_pay.to_param, :size_pay => { "these" => "params" }}, valid_session
      end

      it "assigns the requested size_pay as @size_pay" do
        size_pay = SizePay.create! valid_attributes
        put :update, {:id => size_pay.to_param, :size_pay => valid_attributes}, valid_session
        assigns(:size_pay).should eq(size_pay)
      end

      it "redirects to the size_pay" do
        size_pay = SizePay.create! valid_attributes
        put :update, {:id => size_pay.to_param, :size_pay => valid_attributes}, valid_session
        response.should redirect_to(size_pay)
      end
    end

    describe "with invalid params" do
      it "assigns the size_pay as @size_pay" do
        size_pay = SizePay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SizePay.any_instance.stub(:save).and_return(false)
        put :update, {:id => size_pay.to_param, :size_pay => {  }}, valid_session
        assigns(:size_pay).should eq(size_pay)
      end

      it "re-renders the 'edit' template" do
        size_pay = SizePay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SizePay.any_instance.stub(:save).and_return(false)
        put :update, {:id => size_pay.to_param, :size_pay => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested size_pay" do
      size_pay = SizePay.create! valid_attributes
      expect {
        delete :destroy, {:id => size_pay.to_param}, valid_session
      }.to change(SizePay, :count).by(-1)
    end

    it "redirects to the size_pays list" do
      size_pay = SizePay.create! valid_attributes
      delete :destroy, {:id => size_pay.to_param}, valid_session
      response.should redirect_to(size_pays_url)
    end
  end

end
